name: jaffle_shop_dbtvault
profile: jaffle_shop
version: '1.0.0'
config-version: 2

analysis-paths:
  - analysis
clean-targets:
  - target
seed-paths:
  - data

macro-paths:
  - macros
model-paths:
  - models
test-paths:
  - tests
target-path: target

clean-targets:
    - "target"
    # - "dbt_modules"

vars:
  load_date: '2024-04-04'

models:
  jaffle_shop_dbtvault:
    bv:
      materialized: view
      tags: ['bv']
      enabled: true
    bussiness_vault:
      materialized: view
      tags: ['bussiness_vault']
      enabled: true
    stage:
      materialized: view
      tags: ['stage']
      enabled: true
    raw_vault:
      tags: ['raw_vault']
      materialized: incremental
      hubs:
        tags:
          - 'hub'
      links:
        tags:
          - 'link'
      sats:
        tags:
          - 'satellite'
